### ISSUE TITLE
Tubing part numbers differ between assembly doc & README.md file

### ISSUE THREAD

**Issue by dcarter** [flyonspeed/OnSpeed-Gen2#1]
File "OnSpeed Generation 2.0v2 Assembly Procedure" - calls for these part numbers:
- P/N 5648K68 
- P/N 5648K67

The README.md file calls for:
- 5255k31
- 5255k12

Which are correct, and can the relevant documents be updated. I haven't checked all the other part numbers between the two docs, but that would also be a good idea.

**Comment by larosta** [comment]
The tubing material was changed for Gen2v3 from that called out in the Gen2v2 assembly document to better make sliding the hoses over the barbed fittings easiest.  The new material is also more flexible.

Either material will work but the preferred McMaster p/n’s are now:

5255k31
UV-Resistant Soft Versilon PVC Plastic Tubing, for Air and Water, 1/16" ID, 1/8" OD, Opaque Black

https://www.mcmaster.com/5255K31

5255k12

UV-Resistant Soft Versilon PVC Plastic Tubing, for Air and Water, 3/32" ID, 5/32" OD, Opaque Black

https://www.mcmaster.com/5255K12
